### ISSUE TITLE
多个bug反馈

### ISSUE THREAD

**Issue by CaffuChin0** [bingqiu456/nonebot-plugin-date-name#3]
1.在两个不同群的话不能同时生效同步时间id
2.id有概率串群，例如我在A群设置，后在B群设置，有可能A群的时间名字会显示我B群的设置，但同（1）无法在B群显示我的时间id
3.设置为管理员依然无法更改群主的群昵称，导致无法进行时间名字的修改。

**Comment by bingqiu456** [comment]
我写的时候 是按qq号分的 没按群号分 ~~应该是~~

**Comment by bingqiu456** [comment]
已经修复 把旧版本的先删除 然后安装新版本
```bash
pip uninstall nonebot-plugin-date-name
```
```bash
pip install nonebot-plugin-date-name==3.0
```

**Comment by bingqiu456** [comment]
3.0版本是按群和qq号分开了 同时用了sqlite
